const STREAM_URI = 'STREAM_URI'
const STREAM_PLAY = 'STREAM_PLAY'
const STREAM_STOP = 'STREAM_STOP'
const STREAM_STOP_ERROR = 'STREAM_STOP_ERROR'
const STREAM_STATUS = 'STREAM_STATUS'
const STREAM_ERROR = 'STREAM_ERROR'
const TIMER_RANGE = 'TIMER_RANGE'
const TIMER_INIT = 'TIMER_INIT'
const TIMER_TICK = 'TIMER_TICK'

export {
  STREAM_URI,
  STREAM_PLAY,
  STREAM_STOP,
  STREAM_STOP_ERROR,
  STREAM_ERROR,
  STREAM_STATUS,
  TIMER_RANGE,
  TIMER_INIT,
  TIMER_TICK
}
